version: "3.8"
services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  ftp-server:
    container_name: ftp-comisiones
    environment:
      - FTP_PASS=$FTP_PASS
      - FTP_USER=$FTP_USER
    image: garethflowers/ftp-server
    ports:
      - '20-21:20-21/tcp'
      - '40000-40009:40000-40009/tcp'
    volumes:
      - '/data:/home/user'

  app:
    depends_on:
      - mysqldb
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
             "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true&cachePrepStmts=true&reWriteBatchedInserts=true&allowPublicKeyRetrieval=true",
             "spring.datasource.username" : "$MYSQLDB_USER",
             "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
             "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
             "spring.jpa.hibernate.ddl-auto" : "update",
             "remote.sftp.host" : "$FTP_USER",
             "remote.sftp.username" : "$FTP_HOST",
             "remote.sftp.password" : "$FTP_PASS",
             "spring.datasource.initialization-mode" : "always",
             "spring.datasource.data" : "classpath:db/data.sql"
           }'
    #volumes:
      #- .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: